#!/bin/bash

function search {
    echo "Searching for '$2', please hold..."
    RESULT=$(curl -s "https://search.stepmaniaonline.net/packs/$2" | grep -o -P '(?<=/link/).*(?=.zip)')
    if [ -z ${RESULT+x} ]; then echo "var is unset"; else echo "var is set to '$var'"; fi
}

function ddl {
    PACK=$(echo "$2" | sed -e 's/ /%20/g')
    echo "$PACK"
    curl -L https://search.stepmania.net/link/"$PACK" -o "$2".zip
}

case "$1" in
    -s) search "$@" ;;
    -d) ddl "$@" ;;
esac

Poggers
