#!/bin/sh

ddl () {
	#make sure the user has set their Songs folder so we can make a variable
	if [ -f "$HOME"/.config/spdl/songs.dir ]; then
		SONGS="$(cat "$HOME/.config/spdl/songs.dir")"
	else
		mkdir -p "$HOME/.config/spdl/"
		touch "$HOME/.config/spdl/songs.dir"
		echo "Please place the path to your Songs directory (WITHOUT A TRAILING SLASH) in ~/.config/spdl/songs.dir (file has been created for you)"
		exit
	fi

	#searching for the pack
	echo "Searching for '$2', please hold..."
	SEARCHTERM=$(echo "$2" | sed "s/ /%20/g" | sed "s/#/%23/g" | sed "s/\^/%5E/g" | sed "s/\!/%21/g")
	RESULT=$(curl -s "https://search.stepmaniaonline.net/packs/$SEARCHTERM" | grep -o -P '(?<=/link/).*(?=.zip)')
	[ "$RESULT" = "" ] && echo "No results found!" && exit
	PACK="$(printf "$RESULT" | fzf --layout=reverse --height 40%)"
	FPACK="$(echo "$PACK" | sed "s/ /%20/g" | sed "s/#/%23/g" | sed "s/\^/%5E/g" | sed "s/\!/%21/g")"
	[ "$FPACK" = "" ] && echo "No pack selected! Terminating." && exit
	[ -d "$SONGS" ] && cd "$SONGS"
	printf "Download starting, this may take a while. You will receive a notification when the download is complete.\n\n"
	curl "https://search.stepmaniaonline.net/static/new/$FPACK.zip" -o "$PACK.zip"
	echo ""
	unzip -qq -o "$PACK.zip" #automatically overwrites pack if it exists
	rm "$PACK.zip"
	[ -f /usr/bin/notify-send ] && $(notify-send "Your download of $PACK is complete" &) || echo "Your download of $PACK is complete"
}

spdl_help () {
	printf 'StepMania Pack Downloader (spdl) by swindlesmccoop

Usage: spdl [-dhs] [pack]
-d, --download: (D)ownload [pack]
-h, --help: Print this (h)elp message

When supplying the pack name, always put the pack name in double quotes
'
	exit
}

#if no parameters are supplied, print help
[ $# -eq 0 ] && spdl_help

#handle arguments
case "$1" in
	-d) ddl "$@" ;;
	--download) ddl "$@" ;;
	-h) spdl_help ;;
	--help) spdl_help ;;
esac
