#!/bin/bash

if [[ -f $HOME/.config/spdl/songs.dir ]]; then
    SONGS=$(cat "$HOME/.config/spdl/songs.dir")
else
    mkdir "$HOME/.config/spdl/"
    touch "$HOME/.config/spdl/songs.dir"
    echo "Please place the path to your Songs directory (WITHOUT A TRAILING SLASH) in ~/.config/spdl/songs.dir"
fi

function search {
    printf "Searching for '$2', please hold...\n\n"
    RESULT=$(curl -s "https://search.stepmaniaonline.net/packs/$2" | grep -o -P '(?<=/link/).*(?=.zip)')
    if [ "$RESULT" == "" ]; then echo "No results found!"; else printf "$RESULT\n\n"; fi
}

function ddl {
    PACK=$(echo "$2" | sed -e 's/ /%20/g')
    printf "Download starting, this may take a while. You will receive a notification when the download is complete.\n\n"
    curl -L "https://search.stepmaniaonline.net/static/new/$PACK.zip" -o "$2.zip"
    notify-send "Your download of $2 is complete" &
    unzip -qq "$2.zip" > /dev/null 2>&1
    rm "$2.zip"
    mv "$2" $SONGS/
}

case "$1" in
    -s) search "$@" ;;
    -d) ddl "$@" ;;
esac

